const SECOND = 1_000;
const MINUTE = 60 * SECOND;

export const QUERY_STALE_TIME = {
  ADMIN_STATS: 2 * MINUTE,
  ADMIN_ACTIVITY: 30 * SECOND,
  ADMIN_DISTRIBUTION: 5 * MINUTE,
  ADMIN_DOCTOR_REVIEWS: 60 * SECOND,
  ADMIN_COURSES: 60 * SECOND,
  ADMIN_COURSE_REVIEWS: 30 * SECOND,
  CLASSROOM_STATUS: 60 * SECOND,
  CLASSROOM_TASKS: 5 * MINUTE,
} as const;